"""Initial migration

Revision ID: f5800358cc64
Revises:
Create Date: 2025-12-19 11:46:24.921830+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f5800358cc64"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column(
            "action",
            sa.Enum(
                "USER_CREATED",
                "USER_UPDATED",
                "USER_DELETED",
                "USER_LOGIN",
                "USER_LOGOUT",
                "USER_VERIFIED",
                "ORDER_CREATED",
                "ORDER_UPDATED",
                "ORDER_STATUS_CHANGED",
                "ORDER_CANCELLED",
                "ESCROW_CREATED",
                "ESCROW_FUNDED",
                "ESCROW_LOCKED",
                "ESCROW_FROZEN",
                "ESCROW_RELEASED",
                "ESCROW_REVERTED",
                "SHARIAH_VALIDATED",
                "SHARIAH_VIOLATION",
                "SHARIAH_REVIEW_REQUESTED",
                "SHARIAH_REVIEW_COMPLETED",
                "AI_EVALUATION_STARTED",
                "AI_EVALUATION_COMPLETED",
                "AI_DECISION_MADE",
                "AI_OVERRIDE",
                "BANK_APPROVAL_REQUESTED",
                "BANK_APPROVED",
                "BANK_REJECTED",
                "DELIVERY_CREATED",
                "DELIVERY_STATUS_CHANGED",
                "DELIVERY_CONFIRMED_BUYER",
                "DELIVERY_CONFIRMED_PROVIDER",
                "DISPUTE_CREATED",
                "DISPUTE_UPDATED",
                "DISPUTE_RESOLVED",
                "SYSTEM_ERROR",
                "SYSTEM_OVERRIDE",
                "CONFIG_CHANGED",
                name="auditaction",
            ),
            nullable=False,
        ),
        sa.Column(
            "entity_type",
            sa.Enum(
                "USER",
                "ORDER",
                "ESCROW",
                "ESCROW_TRANSACTION",
                "DELIVERY",
                "PRODUCT",
                "SHARIAH_RESULT",
                "AI_DECISION",
                "DISPUTE",
                "SYSTEM",
                name="entitytype",
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "actor_type",
            sa.Enum(
                "USER",
                "SYSTEM",
                "AI",
                "BANK",
                "ADMIN",
                "SCHEDULER",
                "WEBHOOK",
                name="actortype",
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_name", sa.String(length=255), nullable=True),
        sa.Column(
            "old_values",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Previous state before change",
        ),
        sa.Column(
            "new_values",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="New state after change",
        ),
        sa.Column(
            "changes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Summary of what changed",
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "correlation_id",
            sa.String(length=100),
            nullable=True,
            comment="Links related audit entries together",
        ),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column(
            "related_entities",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="References to related entities",
        ),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "audit_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.create_index(
        "ix_audit_logs_action_time",
        "audit_logs",
        ["action", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_logs_actor", "audit_logs", ["actor_type", "actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_correlation_id"),
        "audit_logs",
        ["correlation_id"],
        unique=False,
    )
    op.create_index("ix_audit_logs_created", "audit_logs", ["created_at"], unique=False)
    op.create_index(
        "ix_audit_logs_entity", "audit_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "haram_product_keywords",
        sa.Column("keyword", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_haram_product_keywords")),
        sa.UniqueConstraint("keyword", name=op.f("uq_haram_product_keywords_keyword")),
    )
    op.create_table(
        "shariah_rules",
        sa.Column("rule_code", sa.String(length=50), nullable=False),
        sa.Column("rule_name", sa.String(length=255), nullable=False),
        sa.Column("rule_category", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("condition", sa.Text(), nullable=False),
        sa.Column(
            "violation_type",
            sa.Enum(
                "RIBA",
                "GHARAR",
                "MAISIR",
                "HARAM_PRODUCT",
                "HARAM_SERVICE",
                "CONTRACT_VIOLATION",
                "OTHER",
                name="violationtype",
            ),
            nullable=False,
        ),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("applies_to_products", sa.Boolean(), nullable=False),
        sa.Column("applies_to_transactions", sa.Boolean(), nullable=False),
        sa.Column("product_categories", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("shariah_reference", sa.Text(), nullable=True),
        sa.Column("scholarly_opinion", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shariah_rules")),
        sa.UniqueConstraint("rule_code", name=op.f("uq_shariah_rules_rule_code")),
    )
    op.create_index(
        "ix_shariah_rules_active", "shariah_rules", ["is_active"], unique=False
    )
    op.create_index(
        "ix_shariah_rules_category", "shariah_rules", ["rule_category"], unique=False
    )
    op.create_table(
        "system_logs",
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("module", sa.String(length=255), nullable=False),
        sa.Column("function", sa.String(length=255), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("correlation_id", sa.String(length=100), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("exception_type", sa.String(length=255), nullable=True),
        sa.Column("exception_message", sa.Text(), nullable=True),
        sa.Column("stack_trace", sa.Text(), nullable=True),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_logs")),
    )
    op.create_index(
        op.f("ix_system_logs_correlation_id"),
        "system_logs",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        "ix_system_logs_created", "system_logs", ["created_at"], unique=False
    )
    op.create_index("ix_system_logs_level", "system_logs", ["level"], unique=False)
    op.create_index("ix_system_logs_module", "system_logs", ["module"], unique=False)
    op.create_table(
        "user_documents",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("document_type", sa.String(length=50), nullable=False),
        sa.Column("document_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.Column("verification_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_documents")),
    )
    op.create_index(
        op.f("ix_user_documents_user_id"), "user_documents", ["user_id"], unique=False
    )
    op.create_index(
        "ix_user_documents_user_type",
        "user_documents",
        ["user_id", "document_type"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column(
            "keycloak_id",
            sa.UUID(),
            nullable=False,
            comment="Keycloak user ID for authentication sync",
        ),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "BUYER",
                "SELLER",
                "BANK",
                "DELIVERY_PROVIDER",
                "ADMIN",
                "SHARIAH_OFFICER",
                name="userrole",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_VERIFICATION",
                "VERIFICATION_IN_PROGRESS",
                "ACTIVE",
                "SUSPENDED",
                "BLOCKED",
                "INACTIVE",
                name="userstatus",
            ),
            nullable=False,
        ),
        sa.Column("business_name", sa.String(length=255), nullable=True),
        sa.Column("business_registration_number", sa.String(length=100), nullable=True),
        sa.Column(
            "business_type",
            sa.Enum(
                "MSME",
                "WHOLESALER",
                "RETAILER",
                "MANUFACTURER",
                "ISLAMIC_BANK",
                "LOGISTICS",
                "INDIVIDUAL",
                name="businesstype",
            ),
            nullable=True,
        ),
        sa.Column("tax_identification_number", sa.String(length=50), nullable=True),
        sa.Column("address_line_1", sa.String(length=255), nullable=True),
        sa.Column("address_line_2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column(
            "financial_profile",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Financial DNA data for AI credit scoring",
        ),
        sa.Column("total_orders_as_buyer", sa.Integer(), nullable=False),
        sa.Column("total_orders_as_seller", sa.Integer(), nullable=False),
        sa.Column("successful_deliveries", sa.Integer(), nullable=False),
        sa.Column("disputes_initiated", sa.Integer(), nullable=False),
        sa.Column("disputes_lost", sa.Integer(), nullable=False),
        sa.Column("buyer_trust_score", sa.Float(), nullable=True),
        sa.Column("seller_trust_score", sa.Float(), nullable=True),
        sa.Column("shariah_certification", sa.String(length=255), nullable=True),
        sa.Column("is_shariah_compliant", sa.Boolean(), nullable=False),
        sa.Column(
            "verification_documents",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="References to uploaded verification documents",
        ),
        sa.Column("verification_notes", sa.Text(), nullable=True),
        sa.Column("verified_at", sa.String(length=50), nullable=True),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.Column("last_keycloak_sync", sa.String(length=50), nullable=True),
        sa.Column(
            "keycloak_attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Additional attributes from Keycloak",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("keycloak_id", name="uq_users_keycloak_id"),
    )
    op.create_index("ix_users_business_type", "users", ["business_type"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_keycloak_id"), "users", ["keycloak_id"], unique=True)
    op.create_index("ix_users_role_status", "users", ["role", "status"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "products",
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sku", sa.String(length=100), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "FOOD_BEVERAGE",
                "ELECTRONICS",
                "CLOTHING_TEXTILE",
                "AGRICULTURE",
                "MANUFACTURING",
                "RAW_MATERIALS",
                "SERVICES",
                "COSMETICS",
                "PHARMACEUTICALS",
                "OTHER",
                name="productcategory",
            ),
            nullable=False,
        ),
        sa.Column("subcategory", sa.String(length=100), nullable=True),
        sa.Column(
            "shariah_category",
            sa.Enum(
                "HALAL", "HARAM", "MASHBOOH", "PENDING_REVIEW", name="shariahcategory"
            ),
            nullable=False,
        ),
        sa.Column("shariah_notes", sa.Text(), nullable=True),
        sa.Column("shariah_reviewed_by", sa.UUID(), nullable=True),
        sa.Column("shariah_reviewed_at", sa.String(length=50), nullable=True),
        sa.Column(
            "haram_indicators",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Detected haram indicators with confidence scores",
        ),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("min_order_quantity", sa.Integer(), nullable=False),
        sa.Column("max_order_quantity", sa.Integer(), nullable=True),
        sa.Column("stock_quantity", sa.Integer(), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "OUT_OF_STOCK",
                "PENDING_APPROVAL",
                "REJECTED",
                name="productstatus",
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("images", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=500), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column(
            "dimensions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Product dimensions {length, width, height, unit}",
        ),
        sa.Column("shipping_class", sa.String(length=50), nullable=True),
        sa.Column("estimated_delivery_days", sa.Integer(), nullable=False),
        sa.Column("halal_certification", sa.String(length=255), nullable=True),
        sa.Column("certification_expiry", sa.String(length=50), nullable=True),
        sa.Column("certification_body", sa.String(length=255), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Custom product attributes",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["seller_id"], ["users.id"], name=op.f("fk_products_seller_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("sku", name=op.f("uq_products_sku")),
    )
    op.create_index(
        "ix_products_active", "products", ["is_active", "status"], unique=False
    )
    op.create_index("ix_products_category", "products", ["category"], unique=False)
    op.create_index(
        op.f("ix_products_seller_id"), "products", ["seller_id"], unique=False
    )
    op.create_index(
        "ix_products_seller_status", "products", ["seller_id", "status"], unique=False
    )
    op.create_index(
        "ix_products_shariah", "products", ["shariah_category"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("order_number", sa.String(length=50), nullable=False),
        sa.Column("buyer_id", sa.UUID(), nullable=False),
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("bank_id", sa.UUID(), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "buyer_down_payment", sa.Numeric(precision=18, scale=4), nullable=False
        ),
        sa.Column(
            "bank_financing_amount", sa.Numeric(precision=18, scale=4), nullable=False
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "SHARIAH_VALIDATED",
                "AI_EVALUATED",
                "PENDING_BANK_APPROVAL",
                "BANK_APPROVED",
                "FUNDED",
                "PROCESSING",
                "IN_TRANSIT",
                "DELIVERED",
                "DELIVERY_VERIFIED",
                "SETTLED",
                "COMPLETED",
                "CANCELLED",
                "REFUNDED",
                "DISPUTED",
                "BLOCKED",
                "FROZEN",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column("previous_status", sa.String(length=50), nullable=True),
        sa.Column(
            "shariah_status",
            sa.Enum(
                "PENDING",
                "COMPLIANT",
                "NON_COMPLIANT",
                "REQUIRES_REVIEW",
                "VIOLATION_DETECTED",
                name="shariahstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "ai_approval_status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "PENDING_REVIEW",
                "FLAGGED",
                name="aiapprovalstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "bank_approval_status",
            sa.Enum(
                "NOT_REQUESTED",
                "PENDING",
                "APPROVED",
                "REJECTED",
                "REQUIRES_INFO",
                name="bankapprovalstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "contract_type",
            sa.Enum(
                "MURABAHA", "SALAM", "ISTISNA", "MUSAWAMAH", "CASH", name="contracttype"
            ),
            nullable=False,
        ),
        sa.Column("financing_requested", sa.Boolean(), nullable=False),
        sa.Column(
            "ownership_status",
            sa.Enum("SELLER", "IN_TRANSIT", "BUYER", name="ownershipstatus"),
            nullable=False,
        ),
        sa.Column(
            "delivery_address", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("delivery_terms", sa.Text(), nullable=True),
        sa.Column("expected_delivery_date", sa.DateTime(), nullable=True),
        sa.Column("actual_delivery_date", sa.DateTime(), nullable=True),
        sa.Column("buyer_confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("seller_confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("provider_confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("shariah_validated_at", sa.DateTime(), nullable=True),
        sa.Column("ai_evaluated_at", sa.DateTime(), nullable=True),
        sa.Column("bank_approved_at", sa.DateTime(), nullable=True),
        sa.Column("escrow_locked_at", sa.DateTime(), nullable=True),
        sa.Column("escrow_released_at", sa.DateTime(), nullable=True),
        sa.Column("settled_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column(
            "order_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_orders_ck_orders_quantity_positive")
        ),
        sa.CheckConstraint(
            "total_amount >= 0", name=op.f("ck_orders_ck_orders_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["bank_id"], ["users.id"], name=op.f("fk_orders_bank_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["buyer_id"], ["users.id"], name=op.f("fk_orders_buyer_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_orders_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"], ["users.id"], name=op.f("fk_orders_seller_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index(op.f("ix_orders_buyer_id"), "orders", ["buyer_id"], unique=False)
    op.create_index(
        "ix_orders_buyer_status", "orders", ["buyer_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_orders_order_number"), "orders", ["order_number"], unique=True
    )
    op.create_index(
        op.f("ix_orders_product_id"), "orders", ["product_id"], unique=False
    )
    op.create_index(op.f("ix_orders_seller_id"), "orders", ["seller_id"], unique=False)
    op.create_index(
        "ix_orders_seller_status", "orders", ["seller_id", "status"], unique=False
    )
    op.create_index(
        "ix_orders_shariah_ai",
        "orders",
        ["shariah_status", "ai_approval_status"],
        unique=False,
    )
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(
        "ix_orders_status_created", "orders", ["status", "created_at"], unique=False
    )
    op.create_table(
        "product_reviews",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("review_text", sa.Text(), nullable=True),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("moderated_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_reviews_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_product_reviews_reviewer_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_reviews")),
    )
    op.create_index(
        op.f("ix_product_reviews_product_id"),
        "product_reviews",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "ai_decisions",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "risk_score",
            sa.Numeric(precision=5, scale=4),
            nullable=False,
            comment="Overall risk score 0-1 (normalized)",
        ),
        sa.Column(
            "decision",
            sa.Enum("ALLOW", "BLOCK", "REVIEW", name="aidecisiontype"),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Numeric(precision=5, scale=4),
            nullable=False,
            comment="Confidence level 0-1",
        ),
        sa.Column(
            "explanation",
            sa.Text(),
            nullable=True,
            comment="Human-readable explanation of decision",
        ),
        sa.Column(
            "reason",
            sa.Text(),
            nullable=True,
            comment="Legacy field for backward compatibility",
        ),
        sa.Column("fraud_detected", sa.Boolean(), nullable=False),
        sa.Column(
            "fraud_indicators",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Detected fraud patterns and indicators",
        ),
        sa.Column("fraud_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "credit_risk_level",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="creditrisklevel"),
            nullable=True,
        ),
        sa.Column(
            "credit_risk_score",
            sa.Numeric(precision=5, scale=4),
            nullable=True,
            comment="Credit risk score 0-1",
        ),
        sa.Column(
            "delivery_reliability_score",
            sa.Numeric(precision=5, scale=4),
            nullable=True,
            comment="Delivery reliability score 0-1",
        ),
        sa.Column(
            "delivery_risk_factors",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Factors affecting delivery risk",
        ),
        sa.Column(
            "financial_dna_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Buyer financial DNA analysis data",
        ),
        sa.Column("model_version", sa.String(length=50), nullable=True),
        sa.Column("evaluation_method", sa.String(length=50), nullable=False),
        sa.Column("was_overridden", sa.Boolean(), nullable=False),
        sa.Column("override_by", sa.UUID(), nullable=True),
        sa.Column("override_reason", sa.Text(), nullable=True),
        sa.Column("original_decision", sa.String(length=20), nullable=True),
        sa.Column(
            "detailed_report",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Full AI evaluation report",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_ai_decisions_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_decisions")),
    )
    op.create_index(
        "ix_ai_decisions_decision", "ai_decisions", ["decision"], unique=False
    )
    op.create_index(
        op.f("ix_ai_decisions_order_id"), "ai_decisions", ["order_id"], unique=True
    )
    op.create_index(
        "ix_ai_decisions_risk", "ai_decisions", ["risk_score"], unique=False
    )
    op.create_table(
        "deliveries",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=True),
        sa.Column("provider_name", sa.String(length=255), nullable=True),
        sa.Column("tracking_number", sa.String(length=100), nullable=True),
        sa.Column("tracking_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PICKED_UP",
                "IN_TRANSIT",
                "OUT_FOR_DELIVERY",
                "DELIVERED",
                "DELIVERY_FAILED",
                "RETURNED",
                "CANCELLED",
                name="deliverystatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "pickup_address", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "delivery_address", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("estimated_pickup_date", sa.DateTime(), nullable=True),
        sa.Column("actual_pickup_date", sa.DateTime(), nullable=True),
        sa.Column("estimated_delivery_date", sa.DateTime(), nullable=True),
        sa.Column("actual_delivery_date", sa.DateTime(), nullable=True),
        sa.Column("buyer_confirmed", sa.Boolean(), nullable=False),
        sa.Column("buyer_confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("buyer_confirmation_notes", sa.Text(), nullable=True),
        sa.Column("provider_confirmed", sa.Boolean(), nullable=False),
        sa.Column("provider_confirmed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "provider_confirmation_reference", sa.String(length=100), nullable=True
        ),
        sa.Column(
            "provider_confirmation_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "delivery_proof",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="POD data: signature, photo, recipient name",
        ),
        sa.Column("has_issue", sa.Boolean(), nullable=False),
        sa.Column(
            "issue_type",
            sa.Enum(
                "NOT_DELIVERED",
                "WRONG_ITEM",
                "DAMAGED",
                "PARTIAL_DELIVERY",
                "WRONG_ADDRESS",
                "RECIPIENT_UNAVAILABLE",
                "OTHER",
                name="deliveryissuetype",
            ),
            nullable=True,
        ),
        sa.Column("issue_description", sa.Text(), nullable=True),
        sa.Column("issue_reported_at", sa.DateTime(), nullable=True),
        sa.Column("package_weight", sa.Float(), nullable=True),
        sa.Column(
            "package_dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("package_count", sa.Integer(), nullable=False),
        sa.Column("shipping_cost", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "insurance_amount", sa.Numeric(precision=18, scale=4), nullable=False
        ),
        sa.Column("delivery_instructions", sa.Text(), nullable=True),
        sa.Column("ai_validation_status", sa.String(length=50), nullable=True),
        sa.Column("ai_validation_score", sa.Float(), nullable=True),
        sa.Column("ai_validation_notes", sa.Text(), nullable=True),
        sa.Column("ai_validated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "delivery_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_deliveries_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deliveries")),
    )
    op.create_index(
        op.f("ix_deliveries_order_id"), "deliveries", ["order_id"], unique=True
    )
    op.create_index(
        "ix_deliveries_provider", "deliveries", ["provider_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_deliveries_provider_id"), "deliveries", ["provider_id"], unique=False
    )
    op.create_index("ix_deliveries_status", "deliveries", ["status"], unique=False)
    op.create_index(
        op.f("ix_deliveries_tracking_number"),
        "deliveries",
        ["tracking_number"],
        unique=True,
    )
    op.create_table(
        "disputes",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("dispute_number", sa.String(length=50), nullable=False),
        sa.Column("initiator_id", sa.UUID(), nullable=False),
        sa.Column(
            "initiator_type",
            sa.Enum("BUYER", "SELLER", "BANK", "PLATFORM", name="disputeparty"),
            nullable=False,
        ),
        sa.Column("respondent_id", sa.UUID(), nullable=True),
        sa.Column(
            "respondent_type",
            sa.Enum("BUYER", "SELLER", "BANK", "PLATFORM", name="disputeparty"),
            nullable=True,
        ),
        sa.Column(
            "dispute_type",
            sa.Enum(
                "NON_DELIVERY",
                "WRONG_ITEM",
                "DAMAGED_ITEM",
                "QUALITY_ISSUE",
                "QUANTITY_MISMATCH",
                "LATE_DELIVERY",
                "SHARIAH_VIOLATION",
                "FRAUD",
                "PAYMENT_ISSUE",
                "OTHER",
                name="disputetype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPENED",
                "UNDER_REVIEW",
                "AWAITING_RESPONSE",
                "AWAITING_EVIDENCE",
                "IN_MEDIATION",
                "RESOLVED",
                "ESCALATED",
                "CLOSED",
                "CANCELLED",
                name="disputestatus",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("disputed_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="List of evidence items with type, url, description",
        ),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column(
            "resolution",
            sa.Enum(
                "BUYER_FAVOR",
                "SELLER_FAVOR",
                "PARTIAL_REFUND",
                "MUTUAL_AGREEMENT",
                "ESCALATED_EXTERNAL",
                "NO_RESOLUTION",
                name="disputeresolution",
            ),
            nullable=True,
        ),
        sa.Column(
            "resolution_amount", sa.Numeric(precision=18, scale=4), nullable=True
        ),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("response_deadline", sa.DateTime(), nullable=True),
        sa.Column("resolution_deadline", sa.DateTime(), nullable=True),
        sa.Column("is_escalated", sa.Boolean(), nullable=False),
        sa.Column("escalated_at", sa.DateTime(), nullable=True),
        sa.Column("escalation_reason", sa.Text(), nullable=True),
        sa.Column(
            "dispute_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_disputes_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_disputes")),
        sa.UniqueConstraint("dispute_number", name=op.f("uq_disputes_dispute_number")),
    )
    op.create_index(
        "ix_disputes_assigned", "disputes", ["assigned_to", "status"], unique=False
    )
    op.create_index("ix_disputes_initiator", "disputes", ["initiator_id"], unique=False)
    op.create_index(
        op.f("ix_disputes_initiator_id"), "disputes", ["initiator_id"], unique=False
    )
    op.create_index(
        op.f("ix_disputes_order_id"), "disputes", ["order_id"], unique=False
    )
    op.create_index(
        "ix_disputes_order_status", "disputes", ["order_id", "status"], unique=False
    )
    op.create_index("ix_disputes_status", "disputes", ["status"], unique=False)
    op.create_table(
        "escrows",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("escrow_number", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "LOCKED",
                "FROZEN",
                "RELEASED",
                "REVERTED",
                "PARTIALLY_RELEASED",
                name="escrowstatus",
            ),
            nullable=False,
        ),
        sa.Column("previous_status", sa.String(length=50), nullable=True),
        sa.Column("bank_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("buyer_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("released_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("refunded_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("platform_fee", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("bank_id", sa.UUID(), nullable=True),
        sa.Column("bank_reference", sa.String(length=100), nullable=True),
        sa.Column("locked_at", sa.DateTime(), nullable=True),
        sa.Column("frozen_at", sa.DateTime(), nullable=True),
        sa.Column("released_at", sa.DateTime(), nullable=True),
        sa.Column("reverted_at", sa.DateTime(), nullable=True),
        sa.Column("freeze_reason", sa.Text(), nullable=True),
        sa.Column("frozen_by", sa.UUID(), nullable=True),
        sa.Column(
            "release_conditions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Tracks which release conditions are met",
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "refunded_amount >= 0",
            name=op.f("ck_escrows_ck_escrows_refunded_non_negative"),
        ),
        sa.CheckConstraint(
            "released_amount >= 0",
            name=op.f("ck_escrows_ck_escrows_released_non_negative"),
        ),
        sa.CheckConstraint(
            "total_amount >= 0", name=op.f("ck_escrows_ck_escrows_total_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_escrows_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_escrows")),
        sa.UniqueConstraint("escrow_number", name=op.f("uq_escrows_escrow_number")),
    )
    op.create_index(op.f("ix_escrows_order_id"), "escrows", ["order_id"], unique=True)
    op.create_index("ix_escrows_status", "escrows", ["status"], unique=False)
    op.create_table(
        "order_status_history",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("from_status", sa.String(length=50), nullable=True),
        sa.Column("to_status", sa.String(length=50), nullable=False),
        sa.Column("changed_by", sa.UUID(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("trigger_type", sa.String(length=50), nullable=False),
        sa.Column(
            "trigger_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_status_history_order_id_orders"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_status_history")),
    )
    op.create_index(
        "ix_order_status_history_order",
        "order_status_history",
        ["order_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_status_history_order_id"),
        "order_status_history",
        ["order_id"],
        unique=False,
    )
    op.create_table(
        "shariah_results",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "COMPLIANT",
                "NON_COMPLIANT",
                "REQUIRES_REVIEW",
                "VIOLATION_DETECTED",
                name="shariahcompliancestatus",
            ),
            nullable=False,
        ),
        sa.Column("compliance_score", sa.Float(), nullable=True),
        sa.Column("product_is_halal", sa.Boolean(), nullable=False),
        sa.Column("product_category_compliant", sa.Boolean(), nullable=False),
        sa.Column("haram_products_detected", sa.Boolean(), nullable=False),
        sa.Column(
            "haram_indicators",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Detected haram indicators with confidence",
        ),
        sa.Column("transaction_compliant", sa.Boolean(), nullable=False),
        sa.Column("contract_type_valid", sa.Boolean(), nullable=False),
        sa.Column("no_riba_detected", sa.Boolean(), nullable=False),
        sa.Column("no_gharar_detected", sa.Boolean(), nullable=False),
        sa.Column("no_maisir_detected", sa.Boolean(), nullable=False),
        sa.Column(
            "violations",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="List of violations with type, description, severity",
        ),
        sa.Column("violation_count", sa.Integer(), nullable=False),
        sa.Column(
            "primary_violation_type",
            sa.Enum(
                "RIBA",
                "GHARAR",
                "MAISIR",
                "HARAM_PRODUCT",
                "HARAM_SERVICE",
                "CONTRACT_VIOLATION",
                "OTHER",
                name="violationtype",
            ),
            nullable=True,
        ),
        sa.Column(
            "principles_validated",
            postgresql.ARRAY(sa.String()),
            nullable=True,
            comment="List of Shariah principles checked",
        ),
        sa.Column("validation_method", sa.String(length=50), nullable=False),
        sa.Column("rules_applied", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("requires_manual_review", sa.Boolean(), nullable=False),
        sa.Column("review_reason", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("review_decision", sa.String(length=50), nullable=True),
        sa.Column(
            "explanation",
            sa.Text(),
            nullable=True,
            comment="Human-readable explanation of the validation result",
        ),
        sa.Column(
            "detailed_report",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Detailed validation report",
        ),
        sa.Column("validated_at", sa.DateTime(), nullable=False),
        sa.Column("post_approval_check_at", sa.DateTime(), nullable=True),
        sa.Column("post_approval_status", sa.String(length=50), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_shariah_results_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shariah_results")),
    )
    op.create_index(
        op.f("ix_shariah_results_order_id"),
        "shariah_results",
        ["order_id"],
        unique=True,
    )
    op.create_index(
        "ix_shariah_results_status", "shariah_results", ["status"], unique=False
    )
    op.create_index(
        "ix_shariah_results_validated",
        "shariah_results",
        ["validated_at"],
        unique=False,
    )
    op.create_table(
        "delivery_confirmations",
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column(
            "confirmation_type",
            sa.Enum("BUYER", "PROVIDER", "SELLER", "SYSTEM", name="confirmationtype"),
            nullable=False,
        ),
        sa.Column("confirmed_by", sa.UUID(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(), nullable=False),
        sa.Column("confirmation_reference", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("signature_data", sa.Text(), nullable=True),
        sa.Column("photo_urls", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("recipient_name", sa.String(length=255), nullable=True),
        sa.Column("recipient_id", sa.String(length=100), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("verification_method", sa.String(length=50), nullable=True),
        sa.Column(
            "device_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("location", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["deliveries.id"],
            name=op.f("fk_delivery_confirmations_delivery_id_deliveries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_confirmations")),
    )
    op.create_index(
        op.f("ix_delivery_confirmations_delivery_id"),
        "delivery_confirmations",
        ["delivery_id"],
        unique=False,
    )
    op.create_index(
        "ix_delivery_confirmations_type",
        "delivery_confirmations",
        ["delivery_id", "confirmation_type"],
        unique=False,
    )
    op.create_table(
        "delivery_tracking_events",
        sa.Column("delivery_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("event_status", sa.String(length=50), nullable=False),
        sa.Column("event_description", sa.Text(), nullable=False),
        sa.Column("event_timestamp", sa.DateTime(), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column(
            "location_coordinates",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("external_event_id", sa.String(length=100), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["deliveries.id"],
            name=op.f("fk_delivery_tracking_events_delivery_id_deliveries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_tracking_events")),
    )
    op.create_index(
        op.f("ix_delivery_tracking_events_delivery_id"),
        "delivery_tracking_events",
        ["delivery_id"],
        unique=False,
    )
    op.create_index(
        "ix_tracking_events_delivery_time",
        "delivery_tracking_events",
        ["delivery_id", "event_timestamp"],
        unique=False,
    )
    op.create_table(
        "dispute_messages",
        sa.Column("dispute_id", sa.UUID(), nullable=False),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column(
            "sender_type",
            sa.Enum("BUYER", "SELLER", "BANK", "PLATFORM", name="disputeparty"),
            nullable=False,
        ),
        sa.Column("sender_name", sa.String(length=255), nullable=False),
        sa.Column("message_type", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("is_internal", sa.Boolean(), nullable=False),
        sa.Column("visible_to", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dispute_id"],
            ["disputes.id"],
            name=op.f("fk_dispute_messages_dispute_id_disputes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dispute_messages")),
    )
    op.create_index(
        "ix_dispute_messages_dispute",
        "dispute_messages",
        ["dispute_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dispute_messages_dispute_id"),
        "dispute_messages",
        ["dispute_id"],
        unique=False,
    )
    op.create_table(
        "dispute_timeline",
        sa.Column("dispute_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("event_description", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_type", sa.String(length=50), nullable=False),
        sa.Column("from_status", sa.String(length=50), nullable=True),
        sa.Column("to_status", sa.String(length=50), nullable=True),
        sa.Column(
            "timeline_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dispute_id"],
            ["disputes.id"],
            name=op.f("fk_dispute_timeline_dispute_id_disputes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dispute_timeline")),
    )
    op.create_index(
        "ix_dispute_timeline_dispute",
        "dispute_timeline",
        ["dispute_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dispute_timeline_dispute_id"),
        "dispute_timeline",
        ["dispute_id"],
        unique=False,
    )
    op.create_table(
        "escrow_transactions",
        sa.Column("escrow_id", sa.UUID(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "BANK_DEPOSIT",
                "BUYER_DEPOSIT",
                "RELEASE_TO_SELLER",
                "REFUND_TO_BUYER",
                "REFUND_TO_BANK",
                "FEE_DEDUCTION",
                "FREEZE",
                "UNFREEZE",
                name="transactiontype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "REVERSED",
                name="transactionstatus",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("from_account", sa.String(length=100), nullable=True),
        sa.Column("to_account", sa.String(length=100), nullable=True),
        sa.Column("reference_number", sa.String(length=100), nullable=False),
        sa.Column("external_reference", sa.String(length=100), nullable=True),
        sa.Column("initiated_by", sa.UUID(), nullable=True),
        sa.Column("initiator_type", sa.String(length=50), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "transaction_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "amount > 0",
            name=op.f("ck_escrow_transactions_ck_escrow_transactions_amount_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["escrow_id"],
            ["escrows.id"],
            name=op.f("fk_escrow_transactions_escrow_id_escrows"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_escrow_transactions")),
        sa.UniqueConstraint(
            "reference_number", name=op.f("uq_escrow_transactions_reference_number")
        ),
    )
    op.create_index(
        op.f("ix_escrow_transactions_escrow_id"),
        "escrow_transactions",
        ["escrow_id"],
        unique=False,
    )
    op.create_index(
        "ix_escrow_transactions_escrow_type",
        "escrow_transactions",
        ["escrow_id", "transaction_type"],
        unique=False,
    )
    op.create_index(
        "ix_escrow_transactions_status", "escrow_transactions", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_escrow_transactions_status", table_name="escrow_transactions")
    op.drop_index(
        "ix_escrow_transactions_escrow_type", table_name="escrow_transactions"
    )
    op.drop_index(
        op.f("ix_escrow_transactions_escrow_id"), table_name="escrow_transactions"
    )
    op.drop_table("escrow_transactions")
    op.drop_index(op.f("ix_dispute_timeline_dispute_id"), table_name="dispute_timeline")
    op.drop_index("ix_dispute_timeline_dispute", table_name="dispute_timeline")
    op.drop_table("dispute_timeline")
    op.drop_index(op.f("ix_dispute_messages_dispute_id"), table_name="dispute_messages")
    op.drop_index("ix_dispute_messages_dispute", table_name="dispute_messages")
    op.drop_table("dispute_messages")
    op.drop_index(
        "ix_tracking_events_delivery_time", table_name="delivery_tracking_events"
    )
    op.drop_index(
        op.f("ix_delivery_tracking_events_delivery_id"),
        table_name="delivery_tracking_events",
    )
    op.drop_table("delivery_tracking_events")
    op.drop_index("ix_delivery_confirmations_type", table_name="delivery_confirmations")
    op.drop_index(
        op.f("ix_delivery_confirmations_delivery_id"),
        table_name="delivery_confirmations",
    )
    op.drop_table("delivery_confirmations")
    op.drop_index("ix_shariah_results_validated", table_name="shariah_results")
    op.drop_index("ix_shariah_results_status", table_name="shariah_results")
    op.drop_index(op.f("ix_shariah_results_order_id"), table_name="shariah_results")
    op.drop_table("shariah_results")
    op.drop_index(
        op.f("ix_order_status_history_order_id"), table_name="order_status_history"
    )
    op.drop_index("ix_order_status_history_order", table_name="order_status_history")
    op.drop_table("order_status_history")
    op.drop_index("ix_escrows_status", table_name="escrows")
    op.drop_index(op.f("ix_escrows_order_id"), table_name="escrows")
    op.drop_table("escrows")
    op.drop_index("ix_disputes_status", table_name="disputes")
    op.drop_index("ix_disputes_order_status", table_name="disputes")
    op.drop_index(op.f("ix_disputes_order_id"), table_name="disputes")
    op.drop_index(op.f("ix_disputes_initiator_id"), table_name="disputes")
    op.drop_index("ix_disputes_initiator", table_name="disputes")
    op.drop_index("ix_disputes_assigned", table_name="disputes")
    op.drop_table("disputes")
    op.drop_index(op.f("ix_deliveries_tracking_number"), table_name="deliveries")
    op.drop_index("ix_deliveries_status", table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_provider_id"), table_name="deliveries")
    op.drop_index("ix_deliveries_provider", table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_order_id"), table_name="deliveries")
    op.drop_table("deliveries")
    op.drop_index("ix_ai_decisions_risk", table_name="ai_decisions")
    op.drop_index(op.f("ix_ai_decisions_order_id"), table_name="ai_decisions")
    op.drop_index("ix_ai_decisions_decision", table_name="ai_decisions")
    op.drop_table("ai_decisions")
    op.drop_index(op.f("ix_product_reviews_product_id"), table_name="product_reviews")
    op.drop_table("product_reviews")
    op.drop_index("ix_orders_status_created", table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index("ix_orders_shariah_ai", table_name="orders")
    op.drop_index("ix_orders_seller_status", table_name="orders")
    op.drop_index(op.f("ix_orders_seller_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_product_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_order_number"), table_name="orders")
    op.drop_index("ix_orders_buyer_status", table_name="orders")
    op.drop_index(op.f("ix_orders_buyer_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_products_shariah", table_name="products")
    op.drop_index("ix_products_seller_status", table_name="products")
    op.drop_index(op.f("ix_products_seller_id"), table_name="products")
    op.drop_index("ix_products_category", table_name="products")
    op.drop_index("ix_products_active", table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index("ix_users_role_status", table_name="users")
    op.drop_index(op.f("ix_users_keycloak_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index("ix_users_business_type", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_user_documents_user_type", table_name="user_documents")
    op.drop_index(op.f("ix_user_documents_user_id"), table_name="user_documents")
    op.drop_table("user_documents")
    op.drop_index("ix_system_logs_module", table_name="system_logs")
    op.drop_index("ix_system_logs_level", table_name="system_logs")
    op.drop_index("ix_system_logs_created", table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_correlation_id"), table_name="system_logs")
    op.drop_table("system_logs")
    op.drop_index("ix_shariah_rules_category", table_name="shariah_rules")
    op.drop_index("ix_shariah_rules_active", table_name="shariah_rules")
    op.drop_table("shariah_rules")
    op.drop_table("haram_product_keywords")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_index("ix_audit_logs_created", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_correlation_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action_time", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
